# Generated by Django 5.0 on 2023-12-28 06:31

import django.db.models.deletion
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('adhar_card_number', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('identification_marks', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('mail_id', models.EmailField(max_length=254)),
                ('contact_detail', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=255)),
                ('father_qualification', models.CharField(max_length=255)),
                ('father_profession', models.CharField(max_length=255)),
                ('father_designation', models.CharField(max_length=255)),
                ('father_aadhar_card', models.CharField(max_length=20)),
                ('father_mobile_number', models.CharField(max_length=15)),
                ('father_mail_id', models.EmailField(max_length=254)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_qualification', models.CharField(max_length=255)),
                ('mother_profession', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_aadhar_card', models.CharField(max_length=20)),
                ('mother_mobile_number', models.CharField(max_length=15)),
                ('mother_mail_id', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to=student.models.document_upload_path)),
                ('aadhaar_card', models.FileField(blank=True, null=True, upload_to=student.models.document_upload_path)),
                ('poa', models.FileField(blank=True, null=True, upload_to=student.models.document_upload_path)),
                ('poi', models.FileField(blank=True, null=True, upload_to=student.models.document_upload_path)),
                ('tc', models.FileField(blank=True, null=True, upload_to=student.models.document_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(blank=True, max_length=12, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('session', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_details', to='student.student')),
            ],
        ),
    ]
